run:
  tests: true
  skip-dirs:
    - test-updater

linters:
  enable:
    - depguard
    - errcheck
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
  disable:
    - gochecknoglobals # we allow global variables in packages
    - gochecknoinits # we allow inits in packages
    - goconst # we allow repeated values to go un-const'd
    - lll # we allow any line length
    - structcheck # structcheck is disabled because of go1.18
    - unparam # we allow function calls to name unused parameters

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - octalLiteral
      - singleCaseSwitch
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: internal/infra/proxy.go
      text: "G306: Expect WriteFile permissions to be 0600 or less"
